# Generated by Django 4.2.1 on 2023-05-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topping', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaMasterPiece',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topping.topping', to_field='name')),
            ],
            options={
                'unique_together': {('pizza', 'topping')},
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(through='pizza.PizzaMasterPiece', to='topping.topping'),
        ),
    ]
