# Generated by Django 4.2.1 on 2023-05-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizzamasterpiece',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
